### ISSUE TITLE
Crash on M1 Pro when pod install

### ISSUE THREAD

**Issue by TaeKyeongKim** [TaeKyeongKim/sidedish#1]
### [Problem] 
 
`PodProfile` 에 `pod SwiftLint` 를 작성하고 `pod install` 을 진행하는 과정에서 아래와 같은 에러 발생.  
> See Crash Report log file under the one of following:                    
     * ~/Library/Logs/DiagnosticReports                                     
     * /Library/Logs/DiagnosticReports                                      
   for more details.

**Comment by TaeKyeongKim** [comment]
- [참조1](https://github.com/CocoaPods/CocoaPods/issues/11056),[참조2](https://www.vbflash.net/135)  에서 루비로 설치한 cocoaPod 을 삭제하고 brew 로 cocoaPod 을 재설치 하면 된다고함. 

- brew 를 이용해서 설치하려고하는데 brew 가 없다고 함.. [m1 에서 brew 설치 과정](https://velog.io/@tycode4/M1-Homebrew%EC%84%A4%EC%B9%98) 참조하여 brew 설치후 cocoaPod 재설치.

**Comment by BumgeunSong** [comment]
오 저도 이 에러 있었어요

**Comment by BumgeunSong** [comment]
참고! https://stackoverflow.com/questions/64901180/how-to-run-cocoapods-on-apple-silicon-m1/64919058#64919058
